name: Publish

on: workflow_dispatch

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 📝 Fetch Sources
      uses: actions/checkout@v3
    - name: 🛠 Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: 🏗 Restore dependencies
      run: dotnet restore
    - name: 🏗 Build
      run: dotnet build --no-restore --configuration Release
    - name: 🏗 Publish
      run: dotnet nuget push "artifacts/package/release/*.nupkg"
